parameters :
 - name: location
 - name: subscriptionId
 - name: serviceConnection
 - name: parameterRepo
 - name: resourceGroupName
 - name: modulePipeline
 - name: moduleName
   type: string
   default: 'steps.pipeline.yml'
 - name: ParameterFile
   type: string
   default: 'azuredeploy.parameters.json'
 - name: 'TemplateFile'
   type: string
   default: 'azuredeploy.json'

steps:
 - template: ${{ parameters.modulePipeline }}
   parameters:
       subscriptionId: ${{ parameters.subscriptionId }}
       location: ${{ parameters.location }}
       resourceGroupName: ${{ parameters.resourceGroupName }}
       serviceConnection: ${{ parameters.serviceConnection }}
       moduleTemplateFile: ${{ parameters.TemplateFile }}
       moduleParameterFile: ${{ parameters.ParametersFile }}
